Refactor
summa-dev/summa-solvency pull request #139
Opened 2023-08-23 10:28 UTC by enricobottazzi

#133

2023-08-23 12:44 UTC, sifnoc requested changes
Everything looks good to me, but there's a small detail in the comment that needs updating.

2023-08-24 14:37 UTC, enricobottazzi commented on zk_prover/src/circuits/traits.rs
> +    /// Generic method to assign value to a cell in the witness table to advice column `column_index`. `object_to_assign` is label to identify the object being assigned. It is useful for debugging.
Fixed in the latest commit! Thanks as always for your meticulousness

2023-08-24 15:10 UTC, alxkzmn approved these changes

2023-08-24 15:10 UTC, alxkzmn commented on contracts/test/Summa.ts
> +      const jsonData = fs.readFileSync(path.resolve(__dirname, '../../zk_prover/examples/proof_solidity_calldata.json'), 'utf-8');
Nice!

2023-08-24 15:14 UTC, merged