Refactor backend by following internal audit comments
summa-dev/summa-solvency pull request #173
Opened 2023-10-31 15:22 UTC by sifnoc

Updates:
- Create bash script(fixed the revert issue) 
- Removed `address_hashes`
- Refactored `MstInclusionProof` struct
- Fix error propagation on the async functions with try operator
- Fix some assesrt code
- Removed function `get_deployment_address` 

- [ ] Update README
	- [Build a Solvency Verifier Contract](https://github.com/summa-dev/summa-solvency/tree/master/zk_prover#build-a-solvency-verifier-contract): the verifier generated base on specific `ptau` file, `
	- [Generating Verifiers for Backend](https://github.com/summa-dev/summa-solvency/blob/master/backend/README.md#generating-verifiers-for-backend): Introduce bash script instead of
- [ ] Check matter `timestamp` as `u64`

2023-11-01 14:27 UTC, enricobottazzi requested changes

2023-11-01 15:17 UTC, sifnoc commented on backend/README.md
>  ### Generating Verifiers for Backend
Good point! That's missing in here. I will update for that.

2023-11-01 15:56 UTC, enricobottazzi commented on backend/README.md
> +This step is also crucial for two primary reasons:
Exactly!!

2023-11-02 04:34 UTC, alxkzmn reviewed
Why did you decide to remove `get_deployment_address`? Now you need to supply this address manually when creating the signer, and the `deployments` file generation is unnecessary.

2023-11-02 05:17 UTC, sifnoc commented
> Why did you decide to remove `get_deployment_address`? Now you need to supply this address manually when creating the signer, and the `deployments` file generation is unnecessary.

Well, I found that the method `get_deployment_address` was not being used effectively in both the `tests` and `example/summa_solvency_flow`. It seemed more straightforward to retrieve the address directly from the `summa_contract` instance.
 While I can see its potential usefulness in real-world scenarios, it didn't seem necessary for current implementation.
If you have any other examples or scenarios in mind where it could be useful, I'd love to hear your thoughts.

2023-11-02 10:27 UTC, enricobottazzi approved these changes
LGTM ∑

2023-11-02 12:37 UTC, sifnoc commented
@alxkzmn Now the Signer accept `Address` and also `Path` of file contains address as config.

2023-11-03 05:05 UTC, alxkzmn commented
Awesome!

2023-11-03 05:06 UTC, merged