Add circuit audit comments
summa-dev/summa-solvency pull request #191
Opened 2023-11-24 05:52 UTC by alxkzmn

There are two circuit audit comments starting with // Audit:

There are also minor typo fixes as well as some changes suggested by clippy.

2023-11-24 15:39 UTC, sifnoc requested changes

2023-11-24 15:39 UTC, sifnoc commented on zk_prover/src/chips/merkle_sum_tree.rs
> +            // 3 − 1 + 4 − 2 = 0
I understand the issue you've pointed out. A malicious prover could potentially exploit the switch in values at this point:
https://github.com/summa-dev/summa-solvency/blob/7489c53ebdd4dd8bbcb3b45490cccee6426fc7c5/zk_prover/src/chips/merkle_sum_tree.rs#L223-L235

However, considering the example provided, it seems that the constraint would not be satisfied.

$$ 1 * 2 * ( 3 - 2 ) - ( 1 - 3) - ( 2 - 4) = 2 \neq 0 $$

Please correct me if I'm missing something or if I'm wrong.

2023-11-27 03:16 UTC, alxkzmn commented on zk_prover/src/chips/merkle_sum_tree.rs
> +            // 3 − 1 + 4 − 2 = 0
The example is for the case when the swap bit is zero: swap_bit * 2 * (element_r_cur - element_l_cur) - (element_l_next - element_l_cur) - (element_r_cur - element_r_next) = - (element_l_next - element_l_cur) - (element_r_cur - element_r_next) = element_l_cur - element_l_next + element_r_next - element_r_cur

2023-11-27 08:11 UTC, alxkzmn commented on zk_prover/src/chips/merkle_sum_tree.rs
> +            // 3 − 1 + 4 − 2 = 0
For example, 3 - 4 + 2 - 1 = 0.

2023-11-27 08:46 UTC, sifnoc commented on zk_prover/src/chips/merkle_sum_tree.rs
> +            // 3 − 1 + 4 − 2 = 0
I see. For better understanding in the example, perhaps assigning 5 to `element_l_next` instead of 1 would make it clearer.

2023-11-27 10:38 UTC, enricobottazzi reviewed
I replied to the two audit issues. Let's keep the PR open until we reach an agreement especially for the swapping constraint issue. When we are good, I'm gonna apply the solution for the two issues (together with the clippy fixes) in a separated PR

2023-11-27 11:02 UTC, alxkzmn commented on zk_prover/src/chips/merkle_sum_tree.rs
> +            // 3 − 1 + 4 − 2 = 0
Yes, I think this is the solution.

2023-11-27 14:08 UTC, sifnoc commented on zk_prover/src/chips/merkle_sum_tree.rs
> +            // 3 − 1 + 4 − 2 = 0
Agreed

2023-11-28 16:53 UTC, closed without merging