Put the asset info in the CSV header #183
summa-dev/summa-solvency pull request #192
Opened 2023-11-24 11:52 UTC by alxkzmn

2023-11-24 11:55 UTC, alxkzmn commented
@enricobottazzi @sifnoc we'll also need to modify the CSVs used for benchmarks after this one is merged.

2023-11-25 13:45 UTC, sifnoc requested changes

2023-11-27 04:25 UTC, alxkzmn commented on backend/examples/summa_solvency_flow.rs
> +    let mut round = Round::<4, 2, 14>::new(&signer, Box::new(mst), params_path, timestamp).unwrap();
Done!

2023-11-27 04:56 UTC, sifnoc approved these changes

2023-11-27 07:25 UTC, enricobottazzi requested changes
The PR looks fine. I just have some issue with the naming of this new field on `MerkleSumTree` as `assets`.  While this is technically correct. it sounds confusing in the context of Proof of Solvency, as people associate assets with proof of assets, which is not the case here.

In our context `Asset` can be replaced by `Currency`, `CryptoCurrency` or `Coin`. Open to suggestion

2023-11-27 07:25 UTC, enricobottazzi commented on backend/README.md
> +- `entry_16.csv`: contains the username and asset balance entries for each CEX user (necessary to build the commitment). Asset balance column names have the following format: `balance_<ASSET>_<CHAIN>
I find it confusing to name it `asset balance entries` when these are actually liabilities. Whenever you say `asset balances` I suggest to just remove "asset"

2023-11-27 07:25 UTC, enricobottazzi commented on zk_prover/src/merkle_sum_tree/tree.rs
> +use super::Asset;
Can you use `use crate::merkle_sum_tree::Asset` rather than `super` ? Just for coherence with the rest of the library

2023-11-27 07:25 UTC, enricobottazzi commented on zk_prover/src/merkle_sum_tree/mst.rs
> +    assets: Vec<Asset>,
Naming is confusing

2023-11-27 07:25 UTC, enricobottazzi reviewed
The PR looks fine. I just have some issue with the naming of this new field on `MerkleSumTree` as `assets`.  While this is technically correct. it sounds confusing in the context of Proof of Solvency, as people associate assets with proof of assets, which is not the case here.

In our context `Asset` can be replaced by `Currency`, `CryptoCurrency` or `Coin`. Open to suggestion

2023-11-27 16:45 UTC, enricobottazzi approved these changes
LFG!

2023-11-27 16:46 UTC, merged