PoC KZG openings for the grand sums
summa-dev/summa-solvency pull request #208
Opened 2023-12-05 09:20 UTC by alxkzmn

@enricobottazzi @sifnoc here are my thoughts on the V2 further action plan/TODO list:

    make "user openings" for the proofs of inclusion;
    complete the circuit with the range checks;
    consider the Solidity verifier;
    integrate V2 into the backend;
    create benchmarks;
    consider further parallelization of the grand sum KZG;
    complete the readme.

2023-12-05 11:01 UTC, enricobottazzi requested changes
Great work! The APIs look smooth 

I have a few observations on top of the code-specific comments:

- After viewing the codebase, I'm not sure if creating a separate package is necessary. There are many duplicates from `zk_prover`. Is there any specific reason for it being a separate package? 

- Related to naming, we should avoid naming it v2 externally. Also, as I wrote in the comment, what makes this version cool is the concept of grandsum. KZG is not a novelty as we were using KZG also before.

- In your to-do, you mention the need to add range checks and I think that's why you added the `range` chip folder inside this repo. That chip was designed to fit the `MstInclusionCircuit` which was a very small circuit with `k=11` (usually) and very large range checks over the summation balances (around 14 BYTES). Therefore we had to split the balances in chunks and perform lookup check for each chunk in a small lookup table of 8 bits. This circuit is very different. It will be a very large circuit with potentially `k=27` considering that it needs to fit all custodian's users. All the balances that we need to perform the range check on are not the summation but just user's balances. Therefore I think we can simply use a single lookup table. For example of 3 BYTES. And do a simple range check over this table without any need to split the balances in chunks.

- When you say "make "user openings" for the proofs of inclusion" do you mean username + balances? This is related to the potential attack we discussed if we were only to open the balances

- Can you add to the readme a link to the hackmd document you made to illustrate this technique?

2023-12-05 11:03 UTC, alxkzmn commented on kzg_prover/src/circuits/solvency_v2.rs
> +        // meta.lookup_any("advice cell should be in range [0, 2^8 - 1]", |meta| {
Because it was not working

2023-12-05 11:03 UTC, alxkzmn commented on kzg_prover/src/circuits/utils.rs
> +            constant_terms.push(BigUint::from(0u8));
Should I return Result instead?

2023-12-05 11:09 UTC, alxkzmn commented on kzg_prover/src/circuits/solvency_v2.rs
> +        // meta.lookup_any("advice cell should be in range [0, 2^8 - 1]", |meta| {
I suggest that the range check will be implemented in a separate issue.

2023-12-05 11:10 UTC, alxkzmn commented on kzg_prover/Cargo.toml
> +[patch."https://github.com/privacy-scaling-explorations/halo2?rev=v2023_04_20"]
Some leftovers, will remove.

2023-12-05 11:12 UTC, alxkzmn commented on kzg_prover/src/circuits/utils.rs
> +        // Skip the balances column commitment
It's a leftover.

2023-12-05 11:36 UTC, alxkzmn commented
@enricobottazzi some replies:

- the reason this is a separate package is because we agreed on it during a meeting 😄 ;
- the username check is not yet there;
- IMHO the range check and readme should be the separate issues not to bloat this pull request.

Regarding the naming - agree with grandsum, but summa_grandsum doesn't sound nice. summa_univariate_grandsum?

2023-12-05 12:06 UTC, alxkzmn commented
@enricobottazzi if we were to put the v2 code into the zk_prover, the old code would have to use the modified Halo2 as well. It's not a big deal, the polynomials can just be ignored. Do you think I can move the v2 code into the zk_prover?

2023-12-05 12:26 UTC, alxkzmn commented on kzg_prover/src/circuits/tests.rs
> +        let (verified, grand_sum) = verify_grand_sum_openings::<N_CURRENCIES>(
Multi-opening will be easy to implement, it's already in Halo2. Can do in a separate task.

2023-12-05 12:39 UTC, enricobottazzi commented on kzg_prover/src/circuits/solvency_v2.rs
> +        // meta.lookup_any("advice cell should be in range [0, 2^8 - 1]", |meta| {
Yes sure! I'd like to it!

2023-12-05 12:46 UTC, enricobottazzi commented
> @enricobottazzi some replies:
> 
> * IMHO the range check and readme should be the separate issues not to bloat this pull request.
> 
> Regarding the naming - agree with grandsum, but summa_grandsum doesn't sound nice. summa_univariate_grandsum?

Agree with these points

> @enricobottazzi if we were to put the v2 code into the zk_prover, the old code would have to use the modified Halo2 as well. It's not a big deal, the polynomials can just be ignored. Do you think I can move the v2 code into the zk_prover?

Yes, I think so.

2023-12-05 12:48 UTC, enricobottazzi reviewed
After moving stuff to `zk_prover`, changes are good to go!

2023-12-05 12:48 UTC, enricobottazzi commented on kzg_prover/src/circuits/utils.rs
> +            constant_terms.push(BigUint::from(0u8));
I now see that the `bool` is returned in `verification_results`. So I think this is fine as it is!

2023-12-08 12:17 UTC, sifnoc requested changes
After reviewing this PR in the context of the "SNARKless Proof Of Solvency for CEX" documentation, my understanding of the implementation has significantly improved. Thank you for your efforts on this.

2023-12-11 06:02 UTC, alxkzmn commented on kzg_prover/src/circuits/tests.rs
> +    // fn test_overflow_solvency_v2() {
Yes, deleted

2023-12-11 08:03 UTC, sifnoc approved these changes
Great! Let's merge

2023-12-11 09:40 UTC, merged