Testing to `v2`
summa-dev/summa-solvency pull request #231
Opened 2023-12-14 13:59 UTC by enricobottazzi

2023-12-18 12:15 UTC, sifnoc requested changes
We might consider mentioning the circuit dimensions in PR #233.
Overall, this looks good to me.

2023-12-18 15:22 UTC, enricobottazzi commented on kzg_prover/src/circuits/tests.rs
> +    fn test_diff_n_users_univariate_grand_sum_full_prover() {
I removed the test. It was just suppose to prove it using 15 entries rather than 16. But I guess it doesn't make much sense

2023-12-18 15:23 UTC, enricobottazzi commented
@sifnoc as you correctly mention, this PR will be affected by #233, therefore I suggest to wait for #233 to be merged first and then apply the changes here

2023-12-19 06:03 UTC, alxkzmn approved these changes
LGTM

2023-12-19 06:55 UTC, enricobottazzi commented on kzg_prover/src/circuits/tests.rs
> +        // In this case, the dimensions are represented by the number fo users.
Fixed in latest

2023-12-19 08:25 UTC, sifnoc approved these changes

2023-12-19 08:28 UTC, merged