Remove `N_BYTES` const generic from `UnivariateGrandSum`
summa-dev/summa-solvency pull request #233
Opened 2023-12-15 13:25 UTC by enricobottazzi

2023-12-18 06:34 UTC, sifnoc requested changes
I am a bit surprised that this implementation of the range-check chip is approximately 30% faster than the previous 8-byte version, even under the same K=17 condition.

I found tiny ones in comments. otherwise, everything looks good to me

2023-12-18 06:34 UTC, sifnoc commented on kzg_prover/src/chips/range/range_check.rs
> +/// `zs[1] = (0x1f2f3f4f5f6 - 0xf5f6) / 2^16 = 0x1f2f3f4`
`zs[0]`and `zs[1]` are missing `f` , It should be ends with `f` like:
= `0x1f2f3f4f5f6`
= `0x1f2f3f4f`

2023-12-19 05:50 UTC, sifnoc approved these changes

2023-12-19 05:55 UTC, alxkzmn approved these changes

2023-12-19 05:57 UTC, merged