Swap snark-verifier for halo2-solidity-verifier
summa-dev/summa-solvency pull request #238
Opened 2023-12-18 10:55 UTC by alxkzmn

2023-12-19 09:41 UTC, enricobottazzi approved these changes
Left minor comments. On top of the PR, I wonder if this new `halo2_solidity_verifier` somehow reduced the size of the deployed contracts. Were you able to benchmark this?

2023-12-19 10:19 UTC, alxkzmn commented on zk_prover/Cargo.toml
> +halo2_proofs = { git = "https://github.com/summa-dev/halo2"}
I was thinking about making a PR but I need to discuss one of the changes I made with Han.

2023-12-19 10:49 UTC, alxkzmn commented
@enricobottazzi the verifier deployment gas usage has reduced a bit from 4822482 to 4228615 (by ~600000), so I guess the bytecode is also smaller.

2023-12-19 10:52 UTC, alxkzmn commented on zk_prover/Cargo.toml
> +halo2_proofs = { git = "https://github.com/summa-dev/halo2"}
I'll explain the fork in the v2 readme.

2023-12-19 14:53 UTC, sifnoc requested changes

2023-12-19 14:53 UTC, sifnoc commented on contracts/package.json
> -    "hardhat": "^2.16.0",
I wasn't sure where to leave a comment about the README, so I'm posting it here.

It seems that running `npx hardhat node` is no longer a prerequisite for executing `npx hardhat test` when testing contracts. Could we consider moving the `npx hardhat node` command line to the Deploying section in the README?

https://github.com/summa-dev/summa-solvency/tree/halo2-verifier/contracts#testing

2023-12-20 07:22 UTC, sifnoc approved these changes

2023-12-20 13:11 UTC, merged