Add initial V2 readme
summa-dev/summa-solvency pull request #250
Opened 2024-01-02 09:44 UTC by alxkzmn

2024-01-03 13:46 UTC, sifnoc requested changes
I think the link given under the Univariate Grand Sum Calculation section covers most of the details.

2024-01-04 06:44 UTC, alxkzmn commented on kzg_prover/README.md
> +The grand total of all the Custodian's $n$ user cryptocurrency balances is the Custodian's liabilities $S$. Summa V2 is using a property of the _sum of all roots of unity in a finite field_ being _eq
This is to make the font _italic_.

2024-01-04 06:44 UTC, alxkzmn commented on kzg_prover/README.md
> +1. construct a polynomial of degree $d = n - 1$ that interpolates the points ($\omega^i$,$b_i$) where $i \in 0..n-1$ is the user index, $\omega^i$ is the power of an $n$-th primitive root of unity ($
I'll add links to the code.

2024-01-04 08:27 UTC, enricobottazzi requested changes

2024-01-04 08:27 UTC, enricobottazzi commented on kzg_prover/README.md
> +Summa V1 was using a Merkle sum tree (MST) as the main data structure and a cryptographic commitment. MST that has $n$ leaves involves hashing operations over $2n-1$ entries, making it computationall
Add link to release version of Summa v1.1 when mentioning it

2024-01-04 08:27 UTC, enricobottazzi commented on kzg_prover/README.md
> +Summa V1 was using a Merkle sum tree (MST) as the main data structure and a cryptographic commitment. MST that has $n$ leaves involves hashing operations over $2n-1$ entries, making it computationall
I would say "MST that has $n$ leaves involves $2n-1$ hashing operations, making it computationally demanding. Additionally, the MST inclusion proofs in Summa V1 have to be wrapped into a ZK-SNARK, making it **unfeasible** to generate all of them at once for the entire user base of the Custodian (~100M users).

2024-01-04 08:27 UTC, enricobottazzi commented on kzg_prover/README.md
> +1. construct a polynomial of degree $d = n - 1$ that interpolates the points ($\omega^i$,$b_i$) where $i \in 0..n-1$ is the user index, $\omega^i$ is the power of an $n$-th primitive root of unity ($
$b_i$ has some formatting error

2024-01-04 08:27 UTC, enricobottazzi commented on kzg_prover/README.md
> +4. Privately provide to each user a KZG opening proof of the corresponding user opening.
Explain what the user opening corresponds to: namely opening of the username + opening of the balances

2024-01-04 08:27 UTC, enricobottazzi commented on kzg_prover/README.md
> +1. Assign all the user balances to an unblinded advice column of the [circuit](../kzg_prover/src/circuits/univariate_grand_sum.rs). The unblinded advice column is a kind of advice column without the
Can you explain why this caracteristic of unblinded advice column is useful for our purpose?

2024-01-04 08:56 UTC, sifnoc commented on kzg_prover/README.md
> +The grand total of all the Custodian's $n$ user cryptocurrency balances is the Custodian's liabilities $S$. Summa V2 is using a property of the _sum of all roots of unity in a finite field_ being _eq
I see, Thanks for tip!

2024-01-04 08:59 UTC, sifnoc commented on kzg_prover/README.md
> +1. construct a polynomial of degree $d = n - 1$ that interpolates the points ($\omega^i$,$b_i$) where $i \in 0..n-1$ is the user index, $\omega^i$ is the power of an $n$-th primitive root of unity ($
It looks correctly displayed on my ide, but broken in github.

2024-01-05 11:34 UTC, enricobottazzi approved these changes

2024-01-05 11:51 UTC, sifnoc approved these changes

2024-01-05 16:31 UTC, merged