Hyperplonk PoC
summa-dev/summa-solvency pull request #285
Opened 2024-04-16 08:14 UTC by alxkzmn

2024-04-18 12:19 UTC, sifnoc requested changes
Thanks for creating the PoC based on HyperPlonk!
I've left a few comments regarding some minor things I found.

2024-04-19 06:49 UTC, alxkzmn commented on prover/src/circuits/summa_circuit.rs
> +            //TODO what's the meaning of this?
I see, thanks! I wonder if it affects the performance in any way.

2024-04-19 06:51 UTC, alxkzmn commented on prover/benches/proof_of_liabilities.rs
> +        17,
Sure

2024-04-22 06:43 UTC, sifnoc approved these changes
Looks good to me!

2024-04-22 06:44 UTC, merged